version: 2
jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/python:3.6.1
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: bank_api_test
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python commands.py create_db
      - run:
          command: |
            . venv/bin/activate
            pytest
      - store_artifacts:
          path: test-reports/
          destination: tr1
