"""empty message

Revision ID: 781445fc4978
Revises: 9a9ecdf38270
Create Date: 2018-09-07 00:12:02.621133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '781445fc4978'
down_revision = '9a9ecdf38270'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('account_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'account_name')
    # ### end Alembic commands ###
