"""empty message

Revision ID: 9a9ecdf38270
Revises: fb8841b18839
Create Date: 2018-09-06 22:31:22.124080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a9ecdf38270'
down_revision = 'fb8841b18839'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_accounts_account_type', table_name='accounts')
    op.drop_index('ix_accounts_email', table_name='accounts')
    op.drop_column('accounts', 'account_type')
    op.drop_column('accounts', 'email')
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=True))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    op.add_column('accounts', sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('accounts', sa.Column('account_type', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.create_index('ix_accounts_email', 'accounts', ['email'], unique=True)
    op.create_index('ix_accounts_account_type', 'accounts', ['account_type'], unique=False)
    # ### end Alembic commands ###
